In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Name of the CSV file
file = 'Airbnb_Austin_Data_Finalized.csv'
Airbnb_Austin_df = pd.read_csv(file)

In [5]:
Airbnb_Austin_df.head()

,summary,zipcode,property_type,accommodates,bedrooms,bathrooms,beds,amenities,square_feet,price,availability_365,cancellation_policy,review_scores_rating,review_scores_value,description,instant_bookable,host_verifications
0,Conveniently located 10-15 from downtown in SW...,78749.0,House,6,1.0,2.5,3.0,"{""Cable TV"",Internet,""Wireless Internet"",""Air ...",3600.0,300.0,240,moderate,100.0,10.0,Conveniently located 10-15 from downtown in SW...,f,"['email', 'facebook', 'linkedin', 'reviews']"
1,Rent this cool concept trailer that has everyt...,78739.0,Camper/RV,2,1.0,0.0,1.0,"{""Air Conditioning"",Heating,""Family/Kid Friend...",NaN,99.0,364,moderate,NaN,NaN,Rent this cool concept trailer that has everyt...,f,"['email', 'phone', 'google', 'kba']"
2,"Upstairs, private, 12ft x 13 1/2ft room. Priv...",78739.0,House,2,1.0,1.5,1.0,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,100.0,365,flexible,NaN,NaN,"Upstairs, private, 12ft x 13 1/2ft room. Priv...",f,"['email', 'phone', 'linkedin', 'jumio']"
3,"Upstairs, private, 11ft x 13 1/2ft room. Priv...",78739.0,House,2,1.0,1.5,1.0,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,100.0,365,flexible,NaN,NaN,"Upstairs, private, 11ft x 13 1/2ft room. Priv...",f,"['email', 'phone', 'linkedin', 'jumio']"
4,Brand-new 3BR/2BA Austin home with landscaped ...,78739.0,House,6,3.0,2.0,3.0,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,599.0,358,strict,NaN,NaN,Brand-new 3BR/2BA Austin home with landscaped ...,f,"['email', 'phone', 'linkedin', 'reviews', 'jum..."

In [6]:
Airbnb_Austin_df.columns

Index(['summary', 'zipcode', 'property_type', 'accommodates', 'bedrooms',
       'bathrooms', 'beds', 'amenities', 'square_feet', 'price',
       'availability_365', 'cancellation_policy', 'review_scores_rating',
       'review_scores_value', 'description', 'instant_bookable',
       'host_verifications'],
      dtype='object')

In [7]:
Cancellations_DF = Airbnb_Austin_df.groupby("cancellation_policy").mean()

In [8]:
Cancellations_DF.head()

,zipcode,accommodates,bedrooms,bathrooms,beds,square_feet,price,availability_365,review_scores_rating,review_scores_value
cancellation_policy,,,,,,,,,,
flexible,78724.491415,3.673299,1.469907,1.348499,1.783116,1199.804878,258.847756,263.730680,95.220165,9.452012
moderate,78720.968134,4.057576,1.588636,1.389058,1.988628,1251.011364,220.286364,260.266667,95.830474,9.472138
no_refunds,78704.000000,6.000000,2.000000,1.000000,4.000000,922.000000,350.000000,365.000000,79.000000,6.000000
strict,78696.923507,5.229522,2.072253,1.652295,2.728516,1375.852941,348.231655,280.277730,95.332599,9.367899
super_strict_30,78740.666667,5.222222,1.555556,1.111111,2.888889,700.000000,346.666667,346.111111,97.888889,9.500000

In [9]:
property_type_DF = Airbnb_Austin_df.groupby('property_type').median()

property_type_DF.loc[:,'price']

property_type
Apartment          150.0
Bed & Breakfast    100.0
Boat                95.0
Bungalow           122.0
Cabin              100.0
Camper/RV           82.5
Chalet             155.0
Condominium        169.0
Earth House        111.5
House              199.0
Hut                 35.0
Loft               175.0
Other              125.0
Tent                14.0
Tipi                40.0
Townhouse          170.0
Treehouse          150.0
Villa              240.0
Name: price, dtype: float64

In [10]:
Airbnb_Austin_df['price'].median()

175.0

In [11]:
property_type_DF['price']['House']

199.0